In [9]:
import pandas as pd

In [10]:
soggetto = "soggetto_7"

In [11]:
# read csv
df = pd.read_csv("Datasets/" + soggetto + '.csv')
df

,SIGMA,TrRi,RiTr,Plu,Ttra,Ttrb,Tr,MeTr,MoTr,RiRi,MoFo,Mmof,MoRi,MeRi,Ri,Comp
0,2.28,1,1,1.00,0.79,0,0.18,1,0.79,0.00,0.79,0,0.00,1,1.00,0.74
1,1.46,1,1,0.68,1.00,0,0.01,1,1.00,0.33,0.66,0,0.33,1,0.68,0.69
2,1.00,1,1,0.00,1.00,0,0.04,1,1.00,1.00,0.04,0,1.00,1,0.00,0.86
3,1.79,1,1,0.20,0.04,0,1.00,1,0.04,0.82,0.75,0,0.82,1,0.20,0.76
4,1.80,1,1,0.00,0.14,0,0.90,1,0.14,1.00,0.90,0,1.00,1,0.00,0.81
5,1.00,1,1,0.01,1.00,0,0.01,1,1.00,1.00,0.01,0,1.00,1,0.01,0.87
6,1.18,1,1,0.42,1.00,0,0.04,1,1.00,0.59,0.38,0,0.59,1,0.42,0.69
7,2.00,1,1,1.00,1.00,0,0.01,1,1.00,0.04,1.00,0,0.04,1,1.00,0.76
8,1.68,1,1,0.09,0.33,0,0.69,1,0.33,1.00,0.57,0,1.00,1,0.09,0.72

In [12]:
# prepare empty dataframe
df_input_1 = pd.DataFrame()
df_input_2 = pd.DataFrame()

In [13]:
SIGMA_MAX = 3

In [14]:
# calculate bit one
df_input_1["SIGMA"] = df.SIGMA
df_input_1["bit_type"] = [1] * len(df)
df_input_1["bit"] = 1 / (1 + (df.SIGMA/SIGMA_MAX))
df_input_2["SIGMA"] = df.SIGMA
df_input_2["bit_type"] = [2] * len(df)
df_input_2["bit"] = 1 - df_input_1["bit"]

In [15]:
df_input_1 = pd.concat([df_input_1, df[df.columns[1:]]], axis=1)
df_input_1

,SIGMA,bit_type,bit,TrRi,RiTr,Plu,Ttra,Ttrb,Tr,MeTr,MoTr,RiRi,MoFo,Mmof,MoRi,MeRi,Ri,Comp
0,2.28,1,0.568182,1,1,1.00,0.79,0,0.18,1,0.79,0.00,0.79,0,0.00,1,1.00,0.74
1,1.46,1,0.672646,1,1,0.68,1.00,0,0.01,1,1.00,0.33,0.66,0,0.33,1,0.68,0.69
2,1.00,1,0.750000,1,1,0.00,1.00,0,0.04,1,1.00,1.00,0.04,0,1.00,1,0.00,0.86
3,1.79,1,0.626305,1,1,0.20,0.04,0,1.00,1,0.04,0.82,0.75,0,0.82,1,0.20,0.76
4,1.80,1,0.625000,1,1,0.00,0.14,0,0.90,1,0.14,1.00,0.90,0,1.00,1,0.00,0.81
5,1.00,1,0.750000,1,1,0.01,1.00,0,0.01,1,1.00,1.00,0.01,0,1.00,1,0.01,0.87
6,1.18,1,0.717703,1,1,0.42,1.00,0,0.04,1,1.00,0.59,0.38,0,0.59,1,0.42,0.69
7,2.00,1,0.600000,1,1,1.00,1.00,0,0.01,1,1.00,0.04,1.00,0,0.04,1,1.00,0.76
8,1.68,1,0.641026,1,1,0.09,0.33,0,0.69,1,0.33,1.00,0.57,0,1.00,1,0.09,0.72

In [16]:
df_input_2 = pd.concat([df_input_2, df[df.columns[1:]]], axis=1)
df_input_2

,SIGMA,bit_type,bit,TrRi,RiTr,Plu,Ttra,Ttrb,Tr,MeTr,MoTr,RiRi,MoFo,Mmof,MoRi,MeRi,Ri,Comp
0,2.28,2,0.431818,1,1,1.00,0.79,0,0.18,1,0.79,0.00,0.79,0,0.00,1,1.00,0.74
1,1.46,2,0.327354,1,1,0.68,1.00,0,0.01,1,1.00,0.33,0.66,0,0.33,1,0.68,0.69
2,1.00,2,0.250000,1,1,0.00,1.00,0,0.04,1,1.00,1.00,0.04,0,1.00,1,0.00,0.86
3,1.79,2,0.373695,1,1,0.20,0.04,0,1.00,1,0.04,0.82,0.75,0,0.82,1,0.20,0.76
4,1.80,2,0.375000,1,1,0.00,0.14,0,0.90,1,0.14,1.00,0.90,0,1.00,1,0.00,0.81
5,1.00,2,0.250000,1,1,0.01,1.00,0,0.01,1,1.00,1.00,0.01,0,1.00,1,0.01,0.87
6,1.18,2,0.282297,1,1,0.42,1.00,0,0.04,1,1.00,0.59,0.38,0,0.59,1,0.42,0.69
7,2.00,2,0.400000,1,1,1.00,1.00,0,0.01,1,1.00,0.04,1.00,0,0.04,1,1.00,0.76
8,1.68,2,0.358974,1,1,0.09,0.33,0,0.69,1,0.33,1.00,0.57,0,1.00,1,0.09,0.72

In [17]:
df_input = pd.concat([df_input_1,df_input_2], axis=0)
df_input.sort_index(inplace=True)
df_input

,SIGMA,bit_type,bit,TrRi,RiTr,Plu,Ttra,Ttrb,Tr,MeTr,MoTr,RiRi,MoFo,Mmof,MoRi,MeRi,Ri,Comp
0,2.28,1,0.568182,1,1,1.00,0.79,0,0.18,1,0.79,0.00,0.79,0,0.00,1,1.00,0.74
0,2.28,2,0.431818,1,1,1.00,0.79,0,0.18,1,0.79,0.00,0.79,0,0.00,1,1.00,0.74
1,1.46,1,0.672646,1,1,0.68,1.00,0,0.01,1,1.00,0.33,0.66,0,0.33,1,0.68,0.69
1,1.46,2,0.327354,1,1,0.68,1.00,0,0.01,1,1.00,0.33,0.66,0,0.33,1,0.68,0.69
2,1.00,1,0.750000,1,1,0.00,1.00,0,0.04,1,1.00,1.00,0.04,0,1.00,1,0.00,0.86
2,1.00,2,0.250000,1,1,0.00,1.00,0,0.04,1,1.00,1.00,0.04,0,1.00,1,0.00,0.86
3,1.79,1,0.626305,1,1,0.20,0.04,0,1.00,1,0.04,0.82,0.75,0,0.82,1,0.20,0.76
3,1.79,2,0.373695,1,1,0.20,0.04,0,1.00,1,0.04,0.82,0.75,0,0.82,1,0.20,0.76
4,1.80,1,0.625000,1,1,0.00,0.14,0,0.90,1,0.14,1.00,0.90,0,1.00,1,0.00,0.81
4,1.80,2,0.375000,1,1,0.00,0.14,0,0.90,1,0.14,1.00,0.90,0,1.00,1,0.00,0.81
5,1.00,1,0.750000,1,1,0.01,1.00,0,0.01,1,1.00,1.00,0.01,0,1.00,1,0.01,0.87
5,1.00,2,0.250000,1,1,0.01,1.00,0,0.01,1,1.00,1.00,0.01,0,1.00,1,0.01,0.87
6,1.18,1,0.717703,1,1,0.42,1.00,0,0.04,1,1.00,0.59,0.38,0,0.59,1,0.42,0.69
6,1.18,2,0.282297,1,1,0.42,1.00,0,0.04,1,1.00,0.59,0.38,0,0.59,1,0.42,0.69
7,2.00,1,0.600000,1,1,1.00,1.00,0,0.01,1,1.00,0.04,1.00,0,0.04,1,1.00,0.76
7,2.00,2,0.400000,1,1,1.00,1.00,0,0.01,1,1.00,0.04,1.00,0,0.04,1,1.00,0.76
8,1.68,1,0.641026,1,1,0.09,0.33,0,0.69,1,0.33,1.00,0.57,0,1.00,1,0.09,0.72
8,1.68,2,0.358974,1,1,0.09,0.33,0,0.69,1,0.33,1.00,0.57,0,1.00,1,0.09,0.72

In [18]:
df_input.to_csv("Datasets/" + soggetto + '_input.csv', index=False)

In [19]:
def calculate_target(dim, sigma, bit_type):
    if bit_type == 1:
        if dim > 0.5:
            return dim - sigma * ( (2 * dim -1)/ 2 )
        else:
            return dim + sigma * ( (1 - 2 * dim)/ 2 )
    else:
        return dim

In [20]:
df_targets = pd.DataFrame()
for col in df_input.columns[3:]:
    list_col = []
    for i in range(0, len(df_input)):
        list_col.append(calculate_target(df_input.iloc[i][col],df_input.iloc[i].SIGMA, df_input.iloc[i].bit_type))
    df_targets[col] = list_col
df_targets

,TrRi,RiTr,Plu,Ttra,Ttrb,Tr,MeTr,MoTr,RiRi,MoFo,Mmof,MoRi,MeRi,Ri,Comp
0,-0.140,-0.140,-0.1400,0.1288,1.140,0.9096,-0.140,0.1288,1.1400,0.1288,1.140,1.1400,-0.140,-0.1400,0.1928
1,1.000,1.000,1.0000,0.7900,0.000,0.1800,1.000,0.7900,0.0000,0.7900,0.000,0.0000,1.000,1.0000,0.7400
2,0.270,0.270,0.4172,0.2700,0.730,0.7254,0.270,0.2700,0.5782,0.4264,0.730,0.5782,0.270,0.4172,0.4126
3,1.000,1.000,0.6800,1.0000,0.000,0.0100,1.000,1.0000,0.3300,0.6600,0.000,0.3300,1.000,0.6800,0.6900
4,0.500,0.500,0.5000,0.5000,0.500,0.5000,0.500,0.5000,0.5000,0.5000,0.500,0.5000,0.500,0.5000,0.5000
5,1.000,1.000,0.0000,1.0000,0.000,0.0400,1.000,1.0000,1.0000,0.0400,0.000,1.0000,1.000,0.0000,0.8600
6,0.105,0.105,0.7370,0.8634,0.895,0.1050,0.105,0.8634,0.2472,0.3025,0.895,0.2472,0.105,0.7370,0.2946
7,1.000,1.000,0.2000,0.0400,0.000,1.0000,1.000,0.0400,0.8200,0.7500,0.000,0.8200,1.000,0.2000,0.7600
8,0.100,0.100,0.9000,0.7880,0.900,0.1800,0.100,0.7880,0.1000,0.1800,0.900,0.1000,0.100,0.9000,0.2520
9,1.000,1.000,0.0000,0.1400,0.000,0.9000,1.000,0.1400,1.0000,0.9000,0.000,1.0000,1.000,0.0000,0.8100
10,0.500,0.500,0.5000,0.5000,0.500,0.5000,0.500,0.5000,0.5000,0.5000,0.500,0.5000,0.500,0.5000,0.5000
11,1.000,1.000,0.0100,1.0000,0.000,0.0100,1.000,1.0000,1.0000,0.0100,0.000,1.0000,1.000,0.0100,0.8700
12,0.410,0.410,0.5144,0.4100,0.590,0.5828,0.410,0.4100,0.4838,0.5216,0.590,0.4838,0.410,0.5144,0.4658
13,1.000,1.000,0.4200,1.0000,0.000,0.0400,1.000,1.0000,0.5900,0.3800,0.000,0.5900,1.000,0.4200,0.6900
14,0.000,0.000,0.0000,0.0000,1.000,0.9900,0.000,0.0000,0.9600,0.0000,1.000,0.9600,0.000,0.0000,0.2400
15,1.000,1.000,1.0000,1.0000,0.000,0.0100,1.000,1.0000,0.0400,1.0000,0.000,0.0400,1.000,1.0000,0.7600
16,0.160,0.160,0.7788,0.6156,0.840,0.3708,0.160,0.6156,0.1600,0.4524,0.840,0.1600,0.160,0.7788,0.3504
17,1.000,1.000,0.0900,0.3300,0.000,0.6900,1.000,0.3300,1.0000,0.5700,0.000,1.0000,1.000,0.0900,0.7200

In [21]:
df_targets.to_csv("Datasets/" + soggetto + '_targets.csv', index=False)